name: Dispatch Deploys

on:
  push:
    branches: [main, qa, dev]
    paths:
      - 'package/*/**'

permissions:
  contents: read
  actions: write

jobs:
  detect-and-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed app folders
        id: changed
        uses: tj-actions/changed-files@v46
        with:
          dir_names: true
          dir_names_max_depth: 1
          files: |
            package/**
          since_last_remote_commit: true

      - name: Debug changed outputs
        run: |
          echo "🔎 All changed files: ${{ steps.changed.outputs.all_changed_files }}"
          echo "🔎 Changed app directories: ${{ steps.changed.outputs.dir_names }}"

      - name: Set environment context
        run: |
          BRANCH=${GITHUB_REF##*/}
          echo "BRANCH_NAME=$BRANCH" >> $GITHUB_ENV
          if [[ "$BRANCH" == "main" ]]; then
            echo "ENV_NAME=prod" >> $GITHUB_ENV
            echo "AWS_ACCOUNT_ID=237041882429" >> $GITHUB_ENV
          else
            echo "ENV_NAME=$BRANCH" >> $GITHUB_ENV
            echo "AWS_ACCOUNT_ID=013360300799" >> $GITHUB_ENV
          fi

      - name: Dispatch deploy workflow for each app
        run: |
          export GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"

          IFS=',' read -ra APPS <<< "${{ steps.changed.outputs.dir_names }}"

          if [ -z "${APPS[*]}" ]; then
            echo "✅ No apps changed, skipping deploy."
            exit 0
          fi

          for path in "${APPS[@]}"; do
            app_name=$(basename "$path")
            echo "🚀 Triggering deploy for $app_name"

            gh workflow run deploy.yml \
              --ref "$BRANCH_NAME" \
              -f app-name="$app_name" \
              -f env-name="$ENV_NAME" \
              -f aws-account-id="$AWS_ACCOUNT_ID" \
              -f s3-bucket="us-east-1-${ENV_NAME}-custom-ui" \
              --title "App Deploy - ${app_name}"
          done
