name: Dispatch Deploys

on:
  push:
    branches: [main, qa, dev, uat]
    paths:
      - 'package/*/**'

permissions:
  contents: read
  actions: write

jobs:
  detect-and-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed app folders
        id: changed
        uses: tj-actions/changed-files@v46
        with:
          dir_names: true
          dir_names_max_depth: 2
          files: |
            package/**

      - name: Get App Names
        id: normalize
        shell: bash
        run: |
          changed_dirs="${{ steps.changed.outputs.all_modified_files }}"

          if [ -z "$changed_dirs" ]; then
            echo "CHANGED_APPS=" >> $GITHUB_ENV
            exit 0
          fi

          apps=$(echo "$changed_dirs" | sed 's|package/||g')
          echo "CHANGED_APPS=$apps" >> $GITHUB_ENV

      - name: Dispatch deploy workflow for each app
        shell: bash
        run: |
          export GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          IFS=',' read -ra APPS <<< "$CHANGED_APPS"

          if [ -z "${APPS[*]}" ]; then
            echo "No apps changed, skipping deploy."
            exit 0
          fi

          for app_name in "${APPS[@]}"; do
            echo "Triggering deploy for $app_name on ${{ github.ref_name }}"
            gh workflow run deploy.yml \
              --ref "${{ github.ref_name }}" \
              -f app-name="$app_name"
          done